### ISSUE TITLE
static arm musl

### ISSUE THREAD

**Issue by ndimiduk** [japaric/rust-cross#21]
How about an arm HF target with static linking via musl?

**Comment by japaric** [comment]
> How about an arm HF target with static linking via musl?

These targets are not in the compiler yet (not in `rustc --print target-list`). But there is a PR that adds them: rust-lang/rust#33189.

After that we need to set the infrastructure to build `std` binaries for those targets. When that is done, you should be able to use the instructions here.

**Comment by japaric** [comment]
The ARM musl targets landed in rust-lang/rust#35060. Required infrastructure work also landed in rust-lang/rust-buildbot#109. Binary releases of `std` for these targets should become available in the next days or weeks.

**Comment by herrernst** [comment]
Should those builds be available at https://static.rust-lang.org/dist/index.html now?

**Comment by japaric** [comment]
@herrernst Sadly, not yet. There were some extra changes needed to support building binaries for _several_ musl targets on the _same_ machine/buildbot that landed just recently (rust-lang/rust#36292). But I think it should be good to go now. Pinging @alexcrichton as a reminder to enable ARM MUSL builds on the production buildbots :smile:.

**Comment by alexcrichton** [comment]
@japaric oh right now adding the ARM MUSL builds aren't trivial unfortunately b/c of the musl-root business. The easiest way to add the builder is to add it to the linux-cross image, but we'd just need to add build system support to bootstrap a bunch of arm musl targets with a bunch of others all at once.

**Comment by polarathene** [comment]
Did anyone get static builds with MUSL on ARM? Just ran into an issue with an old embedded OS(2014, distro no longer receives updates) for armv7 not working due to libc being too old on the system.

**EDIT:** Nevermind, seems the readme docs here haven't been touched since 2017, afaik the ones [here](https://github.com/rust-embedded/cross) on a similar project are where everything happens now.
