### ISSUE TITLE
Change default --target?

### ISSUE THREAD

**Issue by goertzenator** [japaric/rust-cross#24]
Is there any way to change the default compile target?

I've built a rustc that can compile to i586, but it still defaults to i686.  I would like the default to be i586 because I have tooling that currently does not handle the `target/i586-unknown-linux-gnu/xxx` dir layout nicely.

**Comment by japaric** [comment]
> Is there any way to change the default compile target?

Yes, you can set `build.target` in `.cargo/config`:

``` toml
[build]
target = "i586-unknown-linux-gnu"
```

then you won't need to pass `--target`; `cargo build` will compile for the `i586-unknown-linux-gnu` target. However, this would still output the build artifacts to `target/i586-unknown-linux-gnu`.

The only way that I can think of to get a `i586` binary directly in the `target` directory is to use a compiler with host = `i586-unknon-linux-gnu` (see the output of `rustc -Vv`) but the Rust project doesn't have binary releases of `rustc` for that host :-(.

**Comment by goertzenator** [comment]
I've set host, build, and target triples but I always end up with `i686` as the default target.  I wish the Rust project would provide an i586 binary (and i486 too). Anyway, I'm upgrading my [tooling](https://github.com/goertzenator/rust.mk) to deal with `--target`s.  Thanks for your help.

**Comment by japaric** [comment]
> I've set host, build, and target triples but I always end up with i686 as the default target.

Wait, you mean you compiled you own `rustc` with `./configure --host=i586-* --target=i586-* --build=i586-*` and the resulting `rustc` still compiles to `i686` by default? That sounds like a bug to me.

>  I wish the Rust project would provide an i586 binary (and i486 too)

You should open an issue at the rust-lang/rust requesting these binaries. `rustc` for `i586` shouldn't be too hard as there are already releases of `std` for `i586`. `i486` is not even a built-in target right now so `rustc` for that target is going to require way more work.
